<!--
Copyright (C) 2008 TopCoder Inc., All Rights Reserved.

JavaScript Client Project Management 1.0

Author TCSDEVELOPER
-->
<html>
<head>
<title>Helper Unit Test</title>
<script language="JavaScript" type="text/javascript" src="jsunit/app/jsUnitCore.js"></script>
<script language="JavaScript" type="text/javascript" src="../../../../../../../../test_files/AjaxProcessor.js"></script>
<script language="JavaScript" type="text/javascript" src="../../../../../../../../test_files/json2.js"></script>
<script language="JavaScript" type="text/javascript"
    src="../../../../../../main/js/topcoder/clients/bridge/management/client_project_management.js"></script>
<script language="JavaScript" type="text/javascript">

    /**
     * <p>Represent <code>IllegalArgumentException</code> for easy use.</p>
     */
    var IllegalArgumentException = js.topcoder.clients.bridge.management.IllegalArgumentException;

    /**
     * <p>Represent <code>Helper</code> for easy use.</p>
     */
    var Helper = js.topcoder.clients.bridge.management.Helper;

    /**
     * <p>Test method isUndefinedOrNull.</p>
     */
    function testIsUndefinedOrNull() {
        var undefined;
        assertTrue("The result should be true.", Helper.isUndefinedOrNull(undefined));
        assertTrue("The result should be true.", Helper.isUndefinedOrNull(null));

        assertFalse("The result should be true.", Helper.isUndefinedOrNull("str"));
    }

    /**
     * <p>Test method checkType.</p>
     * <p>
     * Verifies that <code>IllegalArgumentException</code> will be thrown if the parameter
     * passed in is not correct type.
     * </p>
     */
    function testCheckType() {
        Helper.checkType("str", "str", "string");

        Helper.checkType(1, "1", "number");

        var failed = false;

        try {
            Helper.checkType("str", "str", "number");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            Helper.checkType(1, "1", "string");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        assertFalse("Fail with invalid parameter.", failed);

    }

    /**
     * <p>Test method checkString.</p>
     * <p>
     * Verifies that <code>IllegalArgumentException</code> will be thrown if the parameter
     * passed in is not string.
     * </p>
     */
    function testCheckString() {
        Helper.checkString("str", "str");

        var failed = false;

        try {
            Helper.checkString(null, "null");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            var undefined;
            Helper.checkString(undefined, "undefined");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            var undefined;
            Helper.checkString(1, "1");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            var undefined;
            Helper.checkString("", "empty");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            var undefined;
            Helper.checkString("	", "empty");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            var undefined;
            Helper.checkString("   ", "trimmed empty");
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        assertFalse("Fail with invalid parameter.", failed);
    }

    /**
     * <p>Test method checkGreaterOrEqual.</p>
     * <p>
     * Verifies that <code>IllegalArgumentException</code> will be thrown if the parameter
     * passed in is smaller than expected.
     * </p>
     */
    function testCheckGreaterOrEqual() {
        Helper.checkGreaterOrEqual(2, "2", 0);

        var failed = false;

        try {
            Helper.checkGreaterOrEqual(null, "null", 0);
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            var undefined;
            Helper.checkGreaterOrEqual(undefined, "undefined", 0);
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        try {
            var undefined;
            Helper.checkGreaterOrEqual(-1, "-1", 0);
            failed = true;
        } catch(e) {
            if (!(e instanceof IllegalArgumentException)){
                fail("The exception is not IllegalArgumentException");
            }
        }

        assertFalse("Fail with invalid parameter.", failed);

    }

    </script>
</head>
<body>
<h1><b>Helper</b> Unit Test</h1>

<p>This page contains Unit Test for <code>Helper</code>
class.</p>
</body>
</html>